# ... (существующий код до около строки 100) ...

os.environ["OUROBOROS_MODEL_FALLBACK_LIST"] = "deepseek/deepseek-r1-0528:free,google/gemma-3-27b-it:free,arcee-ai/trinity-large-preview:free"

# ... (остальной код без изменений) ...